spring:
  application:
    name: telegrambot

bot:
  token: dummy_token

logging:
  level:
    root: info

feign:
  name: botService
  url: http://localhost:8082

logs:
  loki:
    base-url: http://localhost:3100

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus
