spring:
  application:
    name: telegrambot

bot:
  token: dummy_token

logging:
  level:
    root: info
  file:
    name: /app/logs/tgbot.log

feign:
  name: botService
  url: http://localhost:8082
