pipeline {
    agent {
        docker {
            image 'shell2016/agent21jdk_docker_cli:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
            reuseNode true
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'docker version'
            }
        }
    }
}